version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: inctra_pgsql
    env_file:
      - .env.dev
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: