version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: inctra_pgsql_prod
    env_file:
      - ../.env
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backend/app/service/db/base_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    container_name: inctra_backend_prod
    env_file:
      - ../.env.prod
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    # For production, don’t bind mount code
    # volumes:
    #   - ../backend:/app

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    container_name: inctra_frontend_prod
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
